import { spawn } from 'child_process';
import { join, dirname } from 'path';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { ToolContext, ToolResult } from '../types.js';
import { textResult } from '../types.js';
import { requireProjectPath, resolveWithinRoot, buildSafeEnv } from '../helpers.js';
import { forceKillTree } from '../core/process-state.js';
import { executeGdscript } from '../gdscript-executor.js';
import { SCENE_TREE_HEADER, parseGdscriptResult, wrapAssertionCode, opsErrorResult } from './shared.js';
import { gdEscape } from './shared.js';
import { batchValidateScripts } from './validation.js';
import { sendToBridge, setBridgeProjectDir, BRIDGE_READ_ONLY_METHODS } from './game-bridge.js';

// ─── Session State helpers (file-as-memory pattern) ──────────────────────────

export interface SessionState {
  current_task: string;
  epic?: string;
  feature?: string;
  files_modified?: string[];
  decisions?: string[];
  open_questions?: string[];
}

export function formatSessionState(state: SessionState): string {
  const lines: string[] = [
    `# Session State`,
    ``,
    `> Auto-generated by dev_loop save_state`,
    ``,
    `## Current Task`,
    ``,
    state.current_task,
    ``,
  ];

  if (state.epic || state.feature) {
    lines.push(`## Context`);
    lines.push(``);
    if (state.epic) lines.push(`- **Epic**: ${state.epic}`);
    if (state.feature) lines.push(`- **Feature**: ${state.feature}`);
    lines.push(``);
  }

  if (state.files_modified && state.files_modified.length > 0) {
    lines.push(`## Files Modified`);
    lines.push(``);
    for (const f of state.files_modified) lines.push(`- \`${f}\``);
    lines.push(``);
  }

  if (state.decisions && state.decisions.length > 0) {
    lines.push(`## Key Decisions`);
    lines.push(``);
    for (const d of state.decisions) lines.push(`- ${d}`);
    lines.push(``);
  }

  if (state.open_questions && state.open_questions.length > 0) {
    lines.push(`## Open Questions`);
    lines.push(``);
    for (const q of state.open_questions) lines.push(`- [ ] ${q}`);
    lines.push(``);
  }

  return lines.join('\n');
}

export function buildStateBlock(epic: string, feature: string, task: string): string {
  const lines = ['<!-- STATUS -->'];
  if (epic) lines.push(`Epic: ${epic}`);
  if (feature) lines.push(`Feature: ${feature}`);
  if (task) lines.push(`Task: ${task}`);
  lines.push('<!-- /STATUS -->');
  return lines.join('\n');
}

// ─── Tool definitions ──────────────────────────────────────────────────────

// ─── Tool definitions ──────────────────────────────────────────────────────

export function getToolDefinitions(): Tool[] {
  return [
    {
      name: 'workflow',
      description: 'Development workflow tools. dev_loop: execute GDScript with optional validation, bridge queries, and state saving. scene_snapshot: capture structured scene tree snapshot. batch_validate: validate multiple GDScript files at once.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          project_path: { type: 'string', description: 'Path to Godot project directory' },
          action: {
            type: 'string',
            enum: ['dev_loop', 'scene_snapshot', 'batch_validate'],
            description: 'Action type',
          },
          // dev_loop params
          code: { type: 'string', description: 'dev_loop: GDScript code to execute (snippet or full extends SceneTree)' },
          verify: { type: 'boolean', description: 'dev_loop: Also run project validation after execution (default: false)', default: false },
          timeout: { type: 'number', description: 'dev_loop: Timeout per step in seconds (default: 30)', default: 30 },
          load_autoloads: { type: 'boolean', description: 'dev_loop: Load Autoload context (default: true)', default: true },
          bridge: {
            type: 'object',
            description: 'dev_loop: Optional Game Bridge for screenshot/query validation',
            properties: {
              screenshot: {
                type: 'object',
                description: 'Take a screenshot from the running game',
                properties: {
                  path: { type: 'string', description: 'Screenshot save path in game (default: user://mcp_dev_screenshot.png)' },
                },
              },
              queries: {
                type: 'array',
                maxItems: 10,
                description: 'Bridge queries to run after code execution (max 10)',
                items: {
                  type: 'object',
                  properties: {
                    method: { type: 'string', description: 'Bridge query method' },
                    params: { type: 'object', description: 'Query parameters' },
                    expect: { type: 'string', description: 'Expected result substring (optional)' },
                  },
                  required: ['method'],
                },
              },
            },
          },
          acceptance: {
            type: 'object',
            description: 'dev_loop: Optional acceptance criteria',
            properties: {
              assertions: {
                type: 'array',
                description: 'Array of assertions to run after code execution',
                items: {
                  type: 'object',
                  properties: {
                    description: { type: 'string', description: 'Human-readable assertion description' },
                    gdscript: { type: 'string', description: 'GDScript code using _mcp_output to output results' },
                    expect: { type: 'string', description: 'Expected output value (string comparison)' },
                  },
                  required: ['description', 'gdscript'],
                },
              },
            },
          },
          save_state: {
            type: 'object',
            description: 'dev_loop: Save session state to file',
            properties: {
              path: { type: 'string', description: 'State file path relative to project (default: production/session-state/active.md)' },
              task: { type: 'string', description: 'Current task description' },
              epic: { type: 'string', description: 'Epic name (optional)' },
              feature: { type: 'string', description: 'Feature name (optional)' },
              files_modified: {
                type: 'array',
                description: 'List of files modified in this session',
                items: { type: 'string' },
              },
              decisions: {
                type: 'array',
                description: 'Key decisions made',
                items: { type: 'string' },
              },
              open_questions: {
                type: 'array',
                description: 'Unresolved questions',
                items: { type: 'string' },
              },
            },
          },
          // scene_snapshot params
          scene_path: { type: 'string', description: 'scene_snapshot: Scene file path relative to project' },
          max_depth: { type: 'number', description: 'scene_snapshot: Max tree depth (default: 5)', default: 5 },
          // batch_validate params
          scripts: {
            type: 'array',
            description: 'batch_validate: Array of script paths relative to project',
            items: { type: 'string' },
          },
        },
        required: ['project_path', 'action'],
      },
    },
  ];
}


// --- Tool handler ---------------------------------------------------------------

export async function handleTool(name: string, args: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult | null> {
  if (name !== 'workflow') return null;

  const action = args.action as string;
  if (!action) return opsErrorResult('INVALID_PARAMS', '"action" is required (dev_loop, scene_snapshot, or batch_validate).');

  switch (action) {

    case 'dev_loop': {
      const projectPath = requireProjectPath(args);
      const code = args.code as string;
      const verify = args.verify === true;
      const timeout = (args.timeout as number) || 30;
      const loadAutoloads = args.load_autoloads !== false;

      if (!code || typeof code !== 'string') {
        return opsErrorResult('INVALID_PARAMS', '"code" must be a non-empty string.');
      }

      const godot = await ctx.findGodot();
      const execResult = await executeGdscript({
        godotPath: godot,
        projectPath,
        code,
        timeout,
        loadAutoloads,
      });

      const result: Record<string, unknown> = {
        step1_execute: execResult.compile_success ? 'success' : 'compile_error',
      };

      if (!execResult.compile_success) {
        result.compile_error = execResult.compile_error;
        return textResult(JSON.stringify(result, null, 2));
      }

      if (!execResult.run_success) {
        result.step1_execute = 'runtime_error';
        result.run_error = execResult.run_error;
        return textResult(JSON.stringify(result, null, 2));
      }

      const outputs: Record<string, unknown> = {};
      for (const entry of execResult.outputs) {
        try {
          outputs[entry.key] = JSON.parse(entry.value);
        } catch {
          outputs[entry.key] = entry.value;
        }
      }
      result.outputs = outputs;

      if (verify) {
        result.step2_verify = await runVerification(godot, projectPath);
      }

      // ── Bridge step: connect to running game for screenshot/query ──
      const rawBridge = args.bridge;
      const bridge = (rawBridge && typeof rawBridge === 'object' && !Array.isArray(rawBridge))
        ? rawBridge as Record<string, unknown>
        : undefined;
      if (bridge) {
        if (projectPath) {
          setBridgeProjectDir(projectPath);
        }
        const bridgeResult: Record<string, unknown> = { connected: false };
        try {
          // Ping first to verify connectivity
          const pingResp = await sendToBridge('ping', {}, 5000);
          if (pingResp.error) {
            bridgeResult.error = `Bridge ping failed: ${pingResp.error.message}`;
          } else {
            bridgeResult.connected = true;

            // Screenshot
            const screenshot = bridge.screenshot as Record<string, unknown> | undefined;
            if (screenshot) {
              const rawPath = (screenshot.path as string) || 'user://mcp_dev_screenshot.png';
              if (!rawPath.startsWith('user://') && !rawPath.startsWith('res://')) {
                bridgeResult.screenshot = { success: false, error: 'path must start with user:// or res://' };
              } else {
                const ssResp = await sendToBridge('take_screenshot', { path: rawPath }, 10000);
                bridgeResult.screenshot = ssResp.error
                  ? { success: false, error: ssResp.error.message }
                  : { success: true, ...(ssResp.result as Record<string, unknown>) };
              }
            }

            // Queries
            const queries = bridge.queries as Array<Record<string, unknown>> | undefined;
            if (queries && queries.length > 0) {
              const queryResults: Array<Record<string, unknown>> = [];
              for (const q of queries) {
                const method = q.method as string;
                if (!BRIDGE_READ_ONLY_METHODS.has(method)) {
                  queryResults.push({ method, success: false, error: `Method "${method}" not allowed in bridge queries. Allowed: ${[...BRIDGE_READ_ONLY_METHODS].join(', ')}` });
                  continue;
                }
                const params = (q.params as Record<string, unknown>) || {};
                const expect = q.expect as string | undefined;
                const qResp = await sendToBridge(method, params, 10000);
                if (qResp.error) {
                  queryResults.push({ method, success: false, error: qResp.error.message });
                } else {
                  const actual = JSON.stringify(qResp.result);
                  const match = expect ? actual.includes(expect) : undefined;
                  queryResults.push({ method, success: true, result: qResp.result, ...(expect !== undefined ? { match } : {}) });
                }
              }
              bridgeResult.queries = queryResults;
              if (queryResults.length > 0) {
                bridgeResult.all_queries_passed = queryResults.every(r => r.success !== false && (r.match === undefined || r.match === true));
              }
            }
          }
        } catch (err) {
          bridgeResult.error = err instanceof Error ? err.message : String(err);
        }
        const stepNum = verify ? 3 : 2;
        result[`step${stepNum}_bridge`] = bridgeResult;
      }

      // ── Acceptance assertions (execute individually for isolation) ──
      const rawAcceptance = args.acceptance;
      const acceptance = (rawAcceptance && typeof rawAcceptance === 'object' && !Array.isArray(rawAcceptance))
        ? rawAcceptance as Record<string, unknown>
        : undefined;
      if (acceptance) {
        const assertionList = (acceptance.assertions as Array<Record<string, string>>) ?? [];
        if (assertionList.length > 0) {
          const assertionResults: Array<Record<string, unknown>> = [];

          for (let i = 0; i < assertionList.length; i++) {
            const a = assertionList[i];
            const desc = a.description ?? `assertion ${i}`;
            try {
              const wrappedCode = wrapAssertionCode(a.gdscript, desc);
              const assertResult = await executeGdscript({
                godotPath: godot, projectPath, code: wrappedCode, timeout: Math.min(timeout, 15), loadAutoloads,
              });

              if (!assertResult.compile_success) {
                assertionResults.push({ description: desc, passed: false, error: assertResult.compile_error });
              } else if (!assertResult.run_success) {
                assertionResults.push({ description: desc, passed: false, error: assertResult.run_error });
              } else {
                const actual = String(assertResult.outputs.find(e => e.key.startsWith('assert_') || e.key === 'assert_result')?.value ?? '');
                const passed = a.expect ? actual === a.expect : true;
                assertionResults.push({ description: desc, passed, actual, expected: a.expect });
              }
            } catch (err) {
              assertionResults.push({ description: desc, passed: false, error: err instanceof Error ? err.message : String(err) });
            }
          }

          result.acceptance = {
            passed: assertionResults.every(r => r.passed),
            results: assertionResults,
          };
        }
      }

      // ── Step 5: Save State (optional, file-as-memory pattern) ──
      if (args.save_state && typeof args.save_state === 'object') {
        const ss = args.save_state as Record<string, unknown>;
        const statePath = (ss.path as string) || 'production/session-state/active.md';
        const fullStatePath = resolveWithinRoot(projectPath, statePath);
        const dir = dirname(fullStatePath);
        mkdirSync(dir, { recursive: true });
        const content = formatSessionState({
          current_task: (ss.task as string) || 'Unknown task',
          epic: ss.epic as string | undefined,
          feature: ss.feature as string | undefined,
          files_modified: ss.files_modified as string[] | undefined,
          decisions: ss.decisions as string[] | undefined,
          open_questions: ss.open_questions as string[] | undefined,
        });
        writeFileSync(fullStatePath, content, 'utf-8');
        result.save_state = { saved: true, path: statePath };
      }

      return textResult(JSON.stringify(result, null, 2));
    }

    case 'scene_snapshot': {
      const projectPath = requireProjectPath(args);
      const scenePath = args.scene_path as string;
      const maxDepth = (args.max_depth as number) || 5;
      const godot = await ctx.findGodot();

      const safePath = gdEscape(scenePath);
      const snapScript = `${SCENE_TREE_HEADER}

func _initialize():
\tvar packed := load("${safePath}")
\tif packed == null:
\t\t_mcp_output("error", "Failed to load scene: ${safePath}")
\t\t_mcp_done()
\t\treturn
\tvar instance: Node = packed.instantiate()
\t_mcp_get_root().add_child(instance)
\tvar data := _snap(instance, ${maxDepth}, 0)
\t_mcp_output("snapshot", data)
\tinstance.queue_free()
\t_mcp_done()

func _snap(node: Node, max_depth: int, depth: int) -> Dictionary:
\tvar info := {"name": node.name, "type": node.get_class()}
\tif node is Node2D:
\t\tinfo["position"] = {"x": node.position.x, "y": node.position.y}
\t\tinfo["rotation"] = node.rotation
\tif node is Node3D:
\t\tinfo["position"] = {"x": node.position.x, "y": node.position.y, "z": node.position.z}
\tif depth < max_depth:
\t\tvar ch: Array = []
\t\tfor c in node.get_children():
\t\t\tch.append(_snap(c, max_depth, depth + 1))
\t\tinfo["child_count"] = ch.size()
\treturn info
`;

      const result = await executeGdscript({
        godotPath: godot,
        projectPath,
        code: snapScript,
        timeout: 30,
        loadAutoloads: false,
      });

      return parseGdscriptResult(result, [], () => 'SNAPSHOT_FAILED');
    }

    case 'batch_validate': {
      const projectPath = requireProjectPath(args);
      const scripts = args.scripts as string[];

      if (!scripts || !Array.isArray(scripts) || scripts.length === 0) {
        return opsErrorResult('INVALID_PARAMS', '"scripts" must be a non-empty array of file paths.');
      }

      const godot = await ctx.findGodot();
      const fullPaths: string[] = [];
      const missing: string[] = [];

      for (const s of scripts) {
        const full = join(projectPath, s);
        if (existsSync(full)) {
          fullPaths.push(full);
        } else {
          missing.push(s);
        }
      }

      const batchResults = await batchValidateScripts(godot, projectPath, fullPaths, 15000);

      const results: Record<string, unknown> = {};
      let allValid = true;
      let totalFiltered = 0;

      for (const r of batchResults) {
        results[r.file] = r.errors.length > 0 ? { valid: false, error: r.errors } : { valid: true };
        if (r.errors.length > 0) allValid = false;
        if (r.filtered_count) totalFiltered += r.filtered_count;
      }
      for (const m of missing) {
        results[m] = { valid: false, error: 'File not found' };
        allValid = false;
      }

      const summary: Record<string, unknown> = { all_valid: allValid, total: scripts.length, results };
      if (totalFiltered > 0) summary.filtered_count = totalFiltered;

      return textResult(JSON.stringify(summary, null, 2));
    }

    default:
      return textResult(`Unknown action: ${action}. Use "dev_loop", "scene_snapshot", or "batch_validate".`);
  }
}


// --- Helpers -------------------------------------------------------------------

function runVerification(godot: string, projectPath: string): Promise<Record<string, unknown>> {
  return new Promise((resolve) => {
    let out = '';
    const proc = spawn(godot, ['--headless', '--path', projectPath, '-e', '--quit'], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: buildSafeEnv(),
    });

    proc.stdout?.on('data', (d: Buffer) => { out += d.toString(); });
    proc.stderr?.on('data', (d: Buffer) => { out += d.toString(); });

    const timer = setTimeout(() => {
      if (!proc.killed) forceKillTree(proc);
      resolve({ status: 'timeout', output: out.slice(-2000) });
    }, 20000);

    proc.on('close', (code) => {
      clearTimeout(timer);
      const errors = out.split('\n').filter(l => l.includes('ERROR') || l.includes('SCRIPT ERROR'));
      resolve({
        status: code === 0 ? 'passed' : 'failed',
        exit_code: code,
        error_count: errors.length,
        errors: errors.slice(0, 10),
      });
    });

    proc.on('error', (err) => {
      clearTimeout(timer);
      resolve({ status: 'error', message: err.message });
    });
  });
}


export const TOOL_META: Record<string, { readonly: boolean; long_running: boolean }> = {
  workflow: { readonly: false, long_running: true },
};
